# ================================================================================================
# @FileName : application.yml
# @Program : KDW
# @Date : 2022-01-19
# @Description  : 프로젝트 환경 설정
# ================================================================================================

# profiles 설정 (local : 로컬, dev : 개발, real : 운영)
spring:
  profiles:
    active: local

# 로컬 환경 설정
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:sqlserver://218.234.210.90:1433;databaseName=DRP
    username: sa
    password: y^2l1n9cC6
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        use_sql_comments: true
    open-in-view: true
    database-platform: com.jsplan.drp.global.config.MssqlDialectConfig
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
  web:
    locale: ko_KR
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  messages:
    basename: classpath:/messages/message
    encoding: UTF-8
    cache-duration: -1
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
project:
  properties:
    package: com.jsplan.drp
  path:
    domain: http://localhost:3380/
    root: D:\\33_DRP\\workspace\\drp\\src\\main\\resources\\static\\
    upload: D:\\33_DRP\\workspace\\drp\\src\\main\\resources\\static\\upload\\
logging:
  level:
    root: info
    org.springframework.web: debug
    jdbc:
      sqlonly: off
      sqltiming: off
      audit: off
      resultset: off
      resultsettable: off
      connection: off

# 개발 환경 설정
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:sqlserver://218.234.210.90:1433;databaseName=DRP
    username: sa
    password: y^2l1n9cC6
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
  web:
    locale: ko_KR
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  messages:
    basename: classpath:/messages/message
    encoding: UTF-8
    cache-duration: -1
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
project:
  properties:
    package: com.jsplan.drp
  path:
    domain: http://13.209.50.216:3380
    root: /home/ec2-user/tomcat-8.5_drp/webapps/drp/
    upload: /home/ec2-user/tomcat-8.5_drp/webapps/drp/WEB-INF/classes/static/upload/
logging:
  level:
    root: info
    org.springframework.web: debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: debug
      connection: off
